array_animals = [
    ["Cat","Gato","Pets|(animais de estimação)","1"],
    ["Dog","Cachorro, cão","Pets|(animais de estimação)","1"],
    ["Ferret","Furão","Pets|(animais de estimação)","1"],
    ["Guinea pig","Porquinho da Índia","Pets|(animais de estimação)","1"],
    ["Hamster","Hamster","Pets|(animais de estimação)","1"],
    ["Parrot","Papagaio","Pets|(animais de estimação)","1"],
    ["Rabbit","Coelho","Pets|(animais de estimação)","1"],
    ["Bull","Touro","Farm animals|(animais da fazenda)","2"],
    ["Calf","Bezerro","Farm animals|(animais da fazenda)","2"],
    ["Chick","Bezerro","Farm animals|(animais da fazenda)","2"],
    ["Chicken","Galinha, frango","Farm animals|(animais da fazenda)","2"],
    ["Cow","Vaca","Farm animals|(animais da fazenda)","2"],
    ["Donkey","Burro, asno","Farm animals|(animais da fazenda)","2"],
    ["Duck","Pato","Farm animals|(animais da fazenda)","2"],
    ["Frog","Rã / Sapo","Farm animals|(animais da fazenda)","2"],
    ["Goat","Bode","Farm animals|(animais da fazenda)","2"],
    ["Goose","Ganso","Farm animals|(animais da fazenda)","2"],
    ["Horse","Cavalo","Farm animals|(animais da fazenda)","2"],
    ["Mule","Mula","Farm animals|(animais da fazenda)","2"],
    ["Pig","Porco","Farm animals|(animais da fazenda)","2"],
    ["Sheep","Ovelha","Farm animals|(animais da fazenda)","2"],
    ["Albatross","Albatroz","Wild animals|(animais silvestres)","3"],
    ["Alligator","Jacaré","Wild animals|(animais silvestres)","3"],
    ["Armadillo","Tatu","Wild animals|(animais silvestres)","3"],
    ["Bat","Morcego","Wild animals|(animais silvestres)","3"],
    ["Bear","Urso","Wild animals|(animais silvestres)","3"],
    ["Beaver","Castor","Wild animals|(animais silvestres)","3"],
    ["Bird","Pássaro","Wild animals|(animais silvestres)","3"],
    ["Camel","Camelo","Wild animals|(animais silvestres)","3"],
    ["Chameleon","Camaleão","Wild animals|(animais silvestres)","3"],
    ["Coyote","Coiote","Wild animals|(animais silvestres)","3"],
    ["Crocodile","Crocodilo","Wild animals|(animais silvestres)","3"],
    ["Crow","Corvo","Wild animals|(animais silvestres)","3"],
    ["Eagle","Águia","Wild animals|(animais silvestres)","3"],
    ["Elephant","Elefante","Wild animals|(animais silvestres)","3"],
    ["Fox","Raposa","Wild animals|(animais silvestres)","3"],
    ["Giraffe","Girafa","Wild animals|(animais silvestres)","3"],
    ["Hippopotamus/hippo","Hipopótamo","Wild animals|(animais silvestres)","3"],
    ["Kangaroo","Canguru","Wild animals|(animais silvestres)","3"],
    ["Lion","Leão","Wild animals|(animais silvestres)","3"],
    ["Lizard","Lagarto","Wild animals|(animais silvestres)","3"],
    ["Monkey","Macaco","Wild animals|(animais silvestres)","3"],
    ["Moose","Alce","Wild animals|(animais silvestres)","3"],
    ["Mouse","Camundongo","Wild animals|(animais silvestres)","3"],
    ["Orangutan","Orangotango","Wild animals|(animais silvestres)","3"],
    ["Ostrich","Avestruz","Wild animals|(animais silvestres)","3"],
    ["Owl","Coruja","Wild animals|(animais silvestres)","3"],
    ["Panther","Pantera","Wild animals|(animais silvestres)","3"],
    ["Pelican","Pelicano","Wild animals|(animais silvestres)","3"],
    ["Penguin","Pinguim","Wild animals|(animais silvestres)","3"],
    ["Rhino","Rinoceronte","Wild animals|(animais silvestres)","3"],
    ["Sloth","Bicho-preguiça","Wild animals|(animais silvestres)","3"],
    ["Snake","Cobra, serpente","Wild animals|(animais silvestres)","3"],
    ["Squirrel","Esquilo","Wild animals|(animais silvestres)","3"],
    ["Tiger","Tigre","Wild animals|(animais silvestres)","3"],
    ["Tortoise","Jabuti","Wild animals|(animais silvestres)","3"],
    ["Toucan","Tucano","Wild animals|(animais silvestres)","3"],
    ["Wolf","Lobo","Wild animals|(animais silvestres)","3"],
    ["Zebra","Zebra","Wild animals|(animais silvestres)","3"],
    ["Crab","Caranguejo","Marine animals|(animais marinhos)","4"],
    ["Dolphin","Golfinho","Marine animals|(animais marinhos)","4"],
    ["Fish","Peixe","Marine animals|(animais marinhos)","4"],
    ["Mussel","Mexilhão","Marine animals|(animais marinhos)","4"],
    ["Octopus","Polvo","Marine animals|(animais marinhos)","4"],
    ["Seal","Foca","Marine animals|(animais marinhos)","4"],
    ["Shark","Tubarão","Marine animals|(animais marinhos)","4"],
    ["Turtle","Tartaruga","Marine animals|(animais marinhos)","4"],
    ["Whale","Baleia","Marine animals|(animais marinhos)","4"],
    ["Ant","Formiga","Bugs|(insetos)","5"],
    ["Bee","Abelha","Bugs|(insetos)","5"],
    ["Butterfly","Borboleta","Bugs|(insetos)","5"],
    ["Caterpillar","Lagarta","Bugs|(insetos)","5"],
    ["Cockroach","Barata","Bugs|(insetos)","5"],
    ["Cricket","Grilo","Bugs|(insetos)","5"],
    ["Dragonfly","Libélula","Bugs|(insetos)","5"],
    ["Firefly","Vaga-lume","Bugs|(insetos)","5"],
    ["Fly, housefly","Mosca","Bugs|(insetos)","5"],
    ["Ladybug","Joaninha","Bugs|(insetos)","5"],
    ["Mosquito","Mosquito","Bugs|(insetos)","5"],
    ["Spider","Aranha","Bugs|(insetos)","5"],
    ["Capybara","Capivara","Brazilian animals|(animais típicos do Brasil)","6"],
    ["Coati","Quati","Brazilian animals|(animais típicos do Brasil)","6"],
    ["Giant anteater","Tamanduá-bandeira","Brazilian animals|(animais típicos do Brasil)","6"],
    ["Golden lion tamarin","Mico-leão-dourado","Brazilian animals|(animais típicos do Brasil)","6"],
    ["Jaguar","Onça-pintada","Brazilian animals|(animais típicos do Brasil)","6"],
    ["Maned wolf","Lobo-guará","Brazilian animals|(animais típicos do Brasil)","6"],
    ["Pink dolphin","Boto cor-de-rosa","Brazilian animals|(animais típicos do Brasil)","6"]
]